"""
XAUUSD Trading Suite — Professional Dashboard v0.5.1

UI principles:
- Home = chart only.
- Each major function has its own page.
- Demo account and automatic trading have explicit state and controls.
- TP/SL/Entry are displayed only after a final validated signal.
- No synthetic market prices are generated by this dashboard.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path
from datetime import datetime, timezone

import pandas as pd
import streamlit as st

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
if SRC.exists() and str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

st.set_page_config(
    page_title="XAUUSD Trading Suite",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------- Styling ----------
st.markdown("""
<style>
.block-container {padding-top: 1rem; padding-bottom: 1rem; max-width: 1500px;}
[data-testid="stSidebar"] {min-width: 250px; max-width: 280px;}
.metric-card {
    border: 1px solid rgba(128,128,128,.25); border-radius: 12px;
    padding: 12px 14px; background: rgba(128,128,128,.06);
}
.status-ok {color:#16a34a;font-weight:700;}
.status-warn {color:#d97706;font-weight:700;}
.status-bad {color:#dc2626;font-weight:700;}
.small {font-size:.82rem; opacity:.72;}
</style>
""", unsafe_allow_html=True)

# ---------- State ----------
defaults = {
    "df": None,
    "final_signal": None,
    "demo_balance": 10000.0,
    "demo_equity": 10000.0,
    "demo_positions": [],
    "auto_trading": False,
    "demo_mode": True,
    "risk_pct": 1.0,
    "rr": 2.0,
    "last_analysis": None,
}
for k, v in defaults.items():
    if k not in st.session_state:
        st.session_state[k] = v

def load_market_data():
    """Use an uploaded CSV only; never invent market prices."""
    path = st.session_state.get("csv_path")
    if path and Path(path).exists():
        try:
            df = pd.read_csv(path)
            cols = {c.lower(): c for c in df.columns}
            rename = {}
            for wanted in ["open","high","low","close","volume","timestamp","datetime","date","time"]:
                if wanted in cols:
                    rename[cols[wanted]] = wanted
            df = df.rename(columns=rename)
            if "timestamp" not in df.columns:
                for c in ["datetime", "date", "time"]:
                    if c in df.columns:
                        df["timestamp"] = df[c]
                        break
            if "timestamp" in df.columns:
                df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True, errors="coerce")
                df = df.dropna(subset=["timestamp"]).sort_values("timestamp")
            required = ["open","high","low","close"]
            if not all(c in df.columns for c in required):
                return None, "CSV must contain Open, High, Low and Close."
            return df.reset_index(drop=True), None
        except Exception as e:
            return None, f"CSV error: {e}"
    return None, "No real market-data source is connected. Upload a real OHLCV CSV."

def compute_final_signal(df: pd.DataFrame):
    """
    Conservative final-signal layer.
    Entry/SL/TP are created only after direction and validity checks.
    """
    if df is None or len(df) < 50:
        return None, "At least 50 real candles are required."

    d = df.copy()
    for c in ["open","high","low","close"]:
        d[c] = pd.to_numeric(d[c], errors="coerce")
    d = d.dropna(subset=["open","high","low","close"])
    if len(d) < 50:
        return None, "Insufficient valid candles."

    close = float(d["close"].iloc[-1])
    prev = float(d["close"].iloc[-2])
    hi = float(d["high"].tail(20).max())
    lo = float(d["low"].tail(20).min())

    tr = pd.concat([
        d["high"] - d["low"],
        (d["high"] - d["close"].shift()).abs(),
        (d["low"] - d["close"].shift()).abs()
    ], axis=1).max(axis=1)
    atr = float(tr.rolling(14).mean().iloc[-1])
    if not pd.notna(atr) or atr <= 0:
        return None, "ATR unavailable."

    fast = float(d["close"].ewm(span=20, adjust=False).mean().iloc[-1])
    slow = float(d["close"].ewm(span=50, adjust=False).mean().iloc[-1])
    direction = "BUY" if fast > slow and close >= prev else "SELL" if fast < slow and close <= prev else "WAIT"

    if direction == "WAIT":
        return {"status":"WAIT","confidence":50.0}, None

    # Structural stop first; ATR gives a volatility safety buffer.
    if direction == "BUY":
        sl = min(lo, close - 1.25 * atr)
        risk = close - sl
        tp = close + max(2.0 * risk, 1.5 * atr)
        valid = sl < close < tp
    else:
        sl = max(hi, close + 1.25 * atr)
        risk = sl - close
        tp = close - max(2.0 * risk, 1.5 * atr)
        valid = tp < close < sl

    if not valid or risk <= 0:
        return {"status":"WAIT","confidence":0.0}, "Invalid final Entry/SL/TP geometry."

    confidence = 70.0
    if abs(fast - slow) > 0.5 * atr:
        confidence += 10
    if abs(close - prev) > 0.25 * atr:
        confidence += 5

    return {
        "status": direction,
        "confidence": min(confidence, 95.0),
        "entry": close,
        "sl": float(sl),
        "tp": float(tp),
        "risk_distance": float(risk),
        "rr": float(abs(tp-close) / risk),
        "atr": atr,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }, None

def render_chart(df):
    st.subheader("XAUUSD Live Market Chart")
    if df is None or df.empty:
        st.info("Connect a real market-data source or upload real OHLCV data to display the chart.")
        return
    chart = df.copy()
    if "timestamp" in chart.columns:
        chart = chart.set_index("timestamp")
    st.line_chart(chart["close"], height=620)

# ---------- Navigation ----------
pages = [
    "📈 Chart",
    "🎯 Signals",
    "💼 Demo Trading",
    "🤖 Auto Trading",
    "🛡️ Risk Management",
    "🧠 AI Analysis",
    "📊 Backtest",
    "⚙️ Settings",
]
page = st.sidebar.radio("Navigation", pages, index=0)

st.sidebar.divider()
st.sidebar.caption("Data source")
uploaded = st.sidebar.file_uploader("Real OHLCV CSV", type=["csv"])
if uploaded:
    upload_dir = ROOT / ".runtime_uploads"
    upload_dir.mkdir(exist_ok=True)
    csv_path = upload_dir / "market.csv"
    csv_path.write_bytes(uploaded.getbuffer())
    st.session_state["csv_path"] = str(csv_path)

df, data_error = load_market_data()
st.session_state["df"] = df

# ---------- Chart: ONLY chart ----------
if page == "📈 Chart":
    render_chart(df)

# ---------- Signals ----------
elif page == "🎯 Signals":
    st.title("Final Signal Engine")
    st.caption("Entry, SL and TP are shown only after the final signal passes validation.")
    if st.button("Run Final Analysis", type="primary"):
        sig, err = compute_final_signal(df)
        st.session_state["final_signal"] = sig
        st.session_state["last_analysis"] = datetime.now(timezone.utc)
        if err:
            st.error(err)
        else:
            st.success("Final analysis completed.")

    sig = st.session_state.get("final_signal")
    if not sig:
        st.info("No final signal yet. Run analysis.")
    elif sig.get("status") == "WAIT":
        st.warning(f"FINAL SIGNAL: WAIT  | Confidence: {sig.get('confidence',0):.0f}%")
    else:
        c1,c2,c3,c4 = st.columns(4)
        c1.metric("Signal", sig["status"])
        c2.metric("Entry", f'{sig["entry"]:.3f}')
        c3.metric("Stop Loss", f'{sig["sl"]:.3f}')
        c4.metric("Take Profit", f'{sig["tp"]:.3f}')
        st.metric("Risk / Reward", f'{sig["rr"]:.2f}R')
        st.progress(int(sig["confidence"])/100)
        st.caption(f'Confidence: {sig["confidence"]:.0f}% · ATR: {sig["atr"]:.3f}')

# ---------- Demo ----------
elif page == "💼 Demo Trading":
    st.title("Demo Account")
    st.caption("Demo execution is isolated from live broker execution.")
    c1,c2,c3 = st.columns(3)
    c1.metric("Balance", f'${st.session_state["demo_balance"]:,.2f}')
    c2.metric("Equity", f'${st.session_state["demo_equity"]:,.2f}')
    c3.metric("Open Positions", len(st.session_state["demo_positions"]))

    st.subheader("Demo Controls")
    col1,col2 = st.columns(2)
    with col1:
        st.session_state["risk_pct"] = st.number_input("Risk per trade (%)", 0.1, 5.0, float(st.session_state["risk_pct"]), 0.1)
    with col2:
        st.session_state["rr"] = st.number_input("Minimum R/R", 1.0, 10.0, float(st.session_state["rr"]), 0.25)

    sig = st.session_state.get("final_signal")
    if sig and sig.get("status") in ("BUY","SELL"):
        if st.button(f'Execute Demo {sig["status"]}', type="primary"):
            pos = {
                "side": sig["status"], "entry": sig["entry"],
                "sl": sig["sl"], "tp": sig["tp"],
                "risk_pct": st.session_state["risk_pct"],
                "opened_at": datetime.now(timezone.utc).isoformat(),
            }
            st.session_state["demo_positions"].append(pos)
            st.success(f'Demo {sig["status"]} opened at {sig["entry"]:.3f}.')
    else:
        st.info("A final BUY/SELL signal is required before a demo trade can be opened.")

    if st.session_state["demo_positions"]:
        st.dataframe(pd.DataFrame(st.session_state["demo_positions"]), use_container_width=True)

# ---------- Auto trading ----------
elif page == "🤖 Auto Trading":
    st.title("Automatic Trading")
    st.warning("Automatic execution is deliberately gated. A valid final signal and demo mode are required.")
    st.session_state["demo_mode"] = st.toggle("Demo Mode", value=st.session_state["demo_mode"])
    st.session_state["auto_trading"] = st.toggle("Automatic Trading", value=st.session_state["auto_trading"])
    sig = st.session_state.get("final_signal")

    ready = (
        st.session_state["auto_trading"]
        and st.session_state["demo_mode"]
        and sig is not None
        and sig.get("status") in ("BUY","SELL")
        and sig.get("entry") is not None
        and sig.get("sl") is not None
        and sig.get("tp") is not None
    )
    st.write("Execution status:", "🟢 READY" if ready else "🟠 WAITING FOR VALID FINAL SIGNAL")

    if ready and st.button("Execute Current Final Signal"):
        st.session_state["demo_positions"].append({
            "side": sig["status"], "entry": sig["entry"],
            "sl": sig["sl"], "tp": sig["tp"],
            "auto": True, "opened_at": datetime.now(timezone.utc).isoformat()
        })
        st.success("Automatic demo execution completed using the final validated signal.")

# ---------- Risk ----------
elif page == "🛡️ Risk Management":
    st.title("Risk Management")
    st.session_state["risk_pct"] = st.slider("Risk per trade (%)", 0.1, 5.0, float(st.session_state["risk_pct"]), 0.1)
    st.session_state["rr"] = st.slider("Target minimum R/R", 1.0, 10.0, float(st.session_state["rr"]), 0.25)
    st.info("Live position sizing must additionally use the broker's contract specification, tick value, tick size, volume step and account currency.")

# ---------- AI ----------
elif page == "🧠 AI Analysis":
    st.title("AI / Market Intelligence")
    st.info("AI analysis is separated from execution. A model score cannot bypass final-signal, risk, or execution validation.")
    if df is not None:
        sig, err = compute_final_signal(df)
        if err:
            st.warning(err)
        else:
            st.json(sig)

# ---------- Backtest ----------
elif page == "📊 Backtest":
    st.title("Backtest")
    st.info("Use real historical OHLCV. The dashboard does not generate synthetic market data.")
    if df is None:
        st.warning(data_error)
    else:
        st.metric("Candles loaded", len(df))
        st.dataframe(df.tail(100), use_container_width=True)

# ---------- Settings ----------
elif page == "⚙️ Settings":
    st.title("Settings")
    st.write("Runtime")
    st.json({
        "version": "v0.5.1",
        "demo_mode": st.session_state["demo_mode"],
        "automatic_trading": st.session_state["auto_trading"],
        "data_source": "Real CSV upload" if st.session_state.get("csv_path") else "Not connected",
    })
    if st.button("Reset Demo Account"):
        st.session_state["demo_balance"] = 10000.0
        st.session_state["demo_equity"] = 10000.0
        st.session_state["demo_positions"] = []
        st.session_state["final_signal"] = None
        st.success("Demo account reset.")
